spring:
 datasource:
   url: jdbc:sqlserver://LAPTOP-9UFFG6Q9\MSSQLSERVER1:1433;databaseName=DSSP_DB;encrypt=true;trustServerCertificate=true;
   username: amaxx
   password: Very#ard1234
   driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
 jpa:
   hibernate-ddl-auto: update
   generate-ddl: false
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.SQLServer2012Dialect